/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication8;

import java.awt.Font;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Talha Zubair
 */
public class user_quiz extends javax.swing.JFrame {
int Counter=1;
    int numCounter=1;
    int tfCounter=0;
    int mcqsCounter=0;
    int a=100;
    public user_quiz() {
        initComponents();
        
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 0, 0));
        jLabel1.setText("Quiz");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numeric", "MCQS", "TrueFalse" }));

        add.setText("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(add)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       String type=jComboBox1.getSelectedItem().toString();
       
       if(type=="Numeric")
       {
       displayNumeric();
       revalidate();
       repaint();
       }
       else if (type=="TrueFalse")
       {
       displaytrueFalse();
       revalidate();
       repaint();
       }
       else
       {
        displayMCQS();
       revalidate();
       repaint();
       }
    }//GEN-LAST:event_addActionPerformed

    
    public void displayNumeric()
    {
    try {
         FileInputStream fileIn = new FileInputStream("Numeric.txt");
         ObjectInputStream in = new ObjectInputStream(fileIn);
        LinkedList<numeric> numeric_list = (LinkedList<numeric>) in.readObject();
         in.close();
         fileIn.close();
        
         
         
         JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           add(questionLabel);
          
           JTextField Question = new JTextField(numeric_list.get(numCounter).quo.toString(), 50);
            Question.setFont(new Font("Serif", Font.PLAIN, 12));
           Question.setBounds(150, a, 300, 30);
          add(Question);
          
          JLabel ansLabel= new JLabel("Answer : ");
           ansLabel.setFont(new Font("Serif", Font.PLAIN, 12));
          ansLabel.setBounds(50, a+30, 300, 30);
          add(ansLabel);
           
          JTextField Answer = new JTextField("", 50);
            Answer.setFont(new Font("Serif", Font.PLAIN, 12));
           Answer.setBounds(100, a+30, 300, 30);
         add(Answer);
          revalidate();
           repaint();
           numCounter++;
         a+=130;
         Counter++;
         
      }catch(Exception e) {
         e.printStackTrace();
      }
    
    }
     public void displaytrueFalse()
    {
    try {
         FileInputStream fileIn = new FileInputStream("true_false.txt");
         ObjectInputStream in = new ObjectInputStream(fileIn);
        LinkedList<true_false> trueFalse_list = (LinkedList<true_false>) in.readObject();
         in.close();
         fileIn.close();
        
        
         JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           add(questionLabel);
          
           JTextField Question = new JTextField(trueFalse_list.get(tfCounter).quo.toString(), 50);
            Question.setFont(new Font("Serif", Font.PLAIN, 12));
           Question.setBounds(150, a, 300, 30);
          add(Question);
          
          JLabel ansLabel= new JLabel("Answer : ");
           ansLabel.setFont(new Font("Serif", Font.PLAIN, 12));
          ansLabel.setBounds(50, a+30, 300, 30);
          add(ansLabel);
           
         JRadioButton option1 = new JRadioButton("True");
        JRadioButton option2 = new JRadioButton("False");
        option1.setBounds(50, a+60, 300, 30);
        option2.setBounds(50, a+80, 300, 30);
        
          ButtonGroup group = new ButtonGroup();
        group.add(option1);
        group.add(option2);
        add(option1);
        add(option2);
        tfCounter++;
         a+=100;
         Counter++;
         
      }catch(Exception e) {
         e.printStackTrace();
      }
    
    }
      public void displayMCQS()
    {
    try {
         FileInputStream fileIn = new FileInputStream("mcqs.txt");
         ObjectInputStream in = new ObjectInputStream(fileIn);
        LinkedList<mcqs> mcqs_list = (LinkedList<mcqs>) in.readObject();
         in.close();
         fileIn.close();
        
        
         JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           add(questionLabel);
          
           JTextField Question = new JTextField(mcqs_list.get(mcqsCounter).quo.toString(), 50);
            Question.setFont(new Font("Serif", Font.PLAIN, 12));
           Question.setBounds(150, a, 300, 30);
          add(Question);
          
          
           
        JLabel serial1=new JLabel("1 : ");
          serial1.setFont(new Font("Serif", Font.PLAIN, 12));
        serial1.setBounds(30, a+60, 300, 30);
         add(serial1);
           JRadioButton opt1=new JRadioButton("");
           JTextField text1 = new JTextField(mcqs_list.get(mcqsCounter).opt1.toString(), 50);
            text1.setFont(new Font("Serif", Font.PLAIN, 12));
           text1.setBounds(80, a+60, 300, 30);
       add(text1);
           
           
           JLabel serial2=new JLabel("2 : ");
          serial2.setFont(new Font("Serif", Font.PLAIN, 12));
        serial2.setBounds(30, a+80, 300, 30);
         add(serial2);
            JRadioButton opt2=new JRadioButton("");
             JTextField text2 = new JTextField(mcqs_list.get(mcqsCounter).opt2.toString(), 50);
            text2.setFont(new Font("Serif", Font.PLAIN, 12));
           text2.setBounds(80, a+80, 300, 30);
       add(text2);
            
            JLabel serial3=new JLabel("3 : ");
          serial3.setFont(new Font("Serif", Font.PLAIN, 12));
        serial3.setBounds(30, a+100, 300, 30);
          add(serial3);
            JRadioButton opt3=new JRadioButton("");
             JTextField text3 = new JTextField(mcqs_list.get(mcqsCounter).opt3.toString(), 50);
            text3.setFont(new Font("Serif", Font.PLAIN, 12));
           text3.setBounds(80, a+100, 300, 30);
       add(text3);
            
            JLabel serial4=new JLabel("4 : ");
          serial4.setFont(new Font("Serif", Font.PLAIN, 12));
        serial4.setBounds(30, a+120, 300, 30);
          add(serial4);
            JRadioButton opt4=new JRadioButton("");
             JTextField text4 = new JTextField(mcqs_list.get(mcqsCounter).opt4.toString(), 50);
            text4.setFont(new Font("Serif", Font.PLAIN, 12));
           text4.setBounds(80, a+120, 300, 30);
       add(text4);
        
          
      ButtonGroup group1 = new ButtonGroup();
        group1.add(opt1);
        group1.add(opt2);
        group1.add(opt3);
        group1.add(opt4);
        
       
 
        
 
        add(opt1);
        add(opt2);
        add(opt3);
        add(opt4);
        
        mcqsCounter++;
         
         a+=150;
         Counter++;
         
      }catch(Exception e) {
         e.printStackTrace();
      }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_quiz().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
